version: "3"
services:
 bettingrestapi:
  container_name: BettingRestAPI
  build:
   context: ./BettingRestAPI
   dockerfile: ./Dockerfile
  hostname: BettingRestAPI
  ports:
   - 8000:8000
  volumes:
   - ./BettingRestAPI:/src/BettingRestAPI
  command: bash -c 'python manage.py makemigrations && python manage.py migrate && gunicorn BettingRestAPI.wsgi -b 0.0.0.0:8000'
  depends_on:
   - db

 bettingfrontend:
  container_name: BettingFrontend
  build:
   context: ./BettingFrontend
   dockerfile: ./Dockerfile
  image: nginx
  ports:
   - 81:80
  links:
   - bettingrestapi
  environment:
   - NGINX_HOST=betting-predictor.patrick-koss.de
   - NGINX_PORT=80
  volumes:
   - ./templates:/etc/nginx/templates
 
 matchesspider:
  container_name: MatchesSpider
  build:
   context: ./BettingRestAPI
   dockerfile: ./MatchesDockerfile
  links:
   - bettingrestapi
  depends_on:
   - db
  
 statsspider:
  container_name: StatsSpider
  build:
   context: ./BettingRestAPI
   dockerfile: ./StatsDockerfile
  links:
   - bettingrestapi
  depends_on:
   - db

 db:
  image: "postgres"
  environment:
   - "POSTGRES_HOST_AUTH_METHOD=trust"
   - "POSTGRES_PASSWORD=test"
   - "POSTGRES_USER=postgres"
  volumes:
   - postgres_data:/var/lib/postgresql/data/

volumes:
 postgres_data:
