# Generated by Django 3.0.2 on 2020-06-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dpr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kast', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impact', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kpr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('winning_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('Player_1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Player_1', to='csgo_api.Player', verbose_name='Player_1')),
                ('Player_2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Player_2', to='csgo_api.Player', verbose_name='Player_2')),
                ('Player_3', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Player_3', to='csgo_api.Player', verbose_name='Player_3')),
                ('Player_4', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Player_4', to='csgo_api.Player', verbose_name='Player_4')),
                ('Player_5', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Player_5', to='csgo_api.Player', verbose_name='Player_5')),
            ],
        ),
    ]
