# Generated by Django 3.0.2 on 2020-06-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo_api', '0002_auto_20200615_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('team_1_win', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('team_2_win', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('team_1_prediction', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('team_2_prediction', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('Team_1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Team_1_Result', to='csgo_api.Team', verbose_name='Team_1')),
                ('Team_2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Team_2_Result', to='csgo_api.Team', verbose_name='Team_2')),
            ],
        ),
    ]
