# Generated by Django 3.0.2 on 2020-06-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo_api', '0003_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='mode',
            field=models.CharField(default='bo1', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='team_1_confidence',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2_confidence',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
