# Generated by Django 3.0.2 on 2020-06-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo_api', '0004_auto_20200616_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='mode',
            field=models.CharField(default='bo1', max_length=20),
        ),
    ]
