# Generated by Django 3.0.7 on 2020-07-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo_api', '0007_match_prediction_svm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_1_confidence',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_confidence',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
    ]
